---
driver:
  name: terraform
  variables:
    name: Gabriel

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: localhost
      backend: local

platforms:
  - name: os

suites:
  - name: example